export type Item = {
  id: number;
  user_id: number;
  category_id: number;
  title: string;
  description: string;
  price: number;
  trading_status: "selling" | "sold" | string;
  condition: string;
  images: string[];
  image: string;
  is_favorited: boolean;
  user_nickname: string;
  created_by_current_user: boolean;
  created_at: string;
  updated_at: string;
  sale_type?: "fixed_price" | "auction" | "negotiation" | string;
  start_price?: number | null;
  end_at?: string | null;
  min_increment?: number;
  current_bid?: number | null;
  bids_count?: number;
  auction_ended?: boolean;
  winning_bid_amount?: number | null;
  is_current_user_highest_bidder?: boolean;
  can_checkout_auction?: boolean;
  auction_order_id?: number | null;
};
